sudo: false

language: node_js

node_js:
  - 10 # use nodejs v10 LTS

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - cd blog
    - npm install hexo-cli -g

install:
    - yarn install --ignore-engines  # 安装依赖
    - mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"
#    - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ~/bin

branches:
  only:
    - master # build master branch only

script:
#  - reviewdog -conf=.reviewdog.yml -reporter=github-pr-check
  - yarn clean # 清除
  - yarn build # generate static files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: blog/public
