# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Github Pages

on:
  push:
    branches:
      - master
    paths:
      - blog/**
  pull_request:
    paths:
      - blog/**

jobs:
  Pages:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Hexo-Cli
        run: |
          cd blog
          npm i hexo-cli -g

      - name: Install Yarn
        run: |
          cd blog
          npm i yarn -g

      - name: Install dependencies
        run: |
          cd blog
          yarn install
          mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"

      - name: Build docs
        run: |
          cd blog
          yarn run clean
          yarn run build

      # Deploy hexo blog website.
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: blog/public
