# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Github Pages

on:
  push:
    branches:
      - master
    paths:
      - blog/**
  pull_request:
    paths:
      - blog/**

jobs:
  Pages:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Hexo-Cli
        run: cd blog && npm i hexo-cli -g

      - name: Install Yarn
        run: cd blog && npm i yarn -g

      - name: Install dependencies
        run: cd blog && yarn install --ignore-engines && mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"

      - name: Build docs
        run: cd blog && yarn run build

      - name: Deploy docs
        if: ${{ github.event_name == 'push' || inputs.deploy }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: blog/public
          cname: hq1363.github.io
